# Basic options
title: Bioinformatic Enablers
short_name: bioinformatic-enablers
developers: [Jemima Onime, Paul O'Neill]
description: A brief course on bioinformatic analysis.
n_sessions: 3
prereq: NA
url: https://exeter-university-sequencing-facility.github.io/bioinformatic-enablers

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
